language: java
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
 - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
 - heroku plugins:install https://github.com/ddollar/heroku-push

script:
- ./gradlew check
- heroku git:remote -a littlebobbytablestttstaging
- git push heroku master
- ./gradlew seleniumXvfb

deploy:
  provider: heroku
  api_key: e82b9f19-bf7d-434a-9f3b-0bf7fb5bc1dc
  app: littlebobbytablesttt

sudo: required
env:
  HEROKU_API_KEY=e82b9f19-bf7d-434a-9f3b-0bf7fb5bc1dc
  global:
    secure: e82b9f19-bf7d-434a-9f3b-0bf7fb5bc1dc
