language: java
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
 - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
 - heroku plugins:install https://github.com/ddollar/heroku-push

script:
  - ./gradlew check
  - heroku git:remote -a littlebobbytablestttstaging
  - git push heroku master
  - ./gradlew seleniumXvfb

deploy:
  provider: heroku
  api_key: e82b9f19-bf7d-434a-9f3b-0bf7fb5bc1dc
  app: littlebobbytablesttt

env:
  global:
    secure: Mx4ofenfewo6nke41cOgJk/++4qjuvt7SNPGWQLq3wRUapTC2/MlCSZC8ActVebRwnRJCL58aKEzJKy8qQxWC9JwrnGcXH/fhSb2WO7ltUGkojxuCD5BwOla7P9MrVGcOld7f61W5YU/QJK+K7j/Gty/wf1Kq/CmBL6F+9o2xOaXZI30KTgfwNan12ZSVbU6pSaN1MNWa30KsyVZzYnVhFldH3eeobUqY9i9MYRYPZyJDK0UJHmK+n8OmTO50c4ervRBFQ8VFfkTVSdH/S6i2TqTxxTJgSI+Lyd7EJe8+JNqSUXE5IDFeFkI+gvikhltethJr7+n9UWbHFCGfQq5YC8jPVCXOa7+K+Qb8KQRaysLBLfhxyLeEJwjbYxWTMpJh6/2RDjrbHr8Ldrd1Zf9Cm30e91VU8+gCuInjUFyQQXDmqtriCrXciIig39d7uvnwSsSpQxJUxyJHgxhKx8ndta59TsFA9EXV3zq7h3iIG5E4vvlganySETMByhH2c20kT5hW8twd85LwofKteDblaV7JqSq2OoULPAsgmOjdhguj3IKv69M+4AuMGojV26r2GP9/Nctxnd0sjupi/geq8imLqL+mkONaYZ8uO4b/c4xtnYWizGOYdYpL3f59xI7G/y9wmklC0/FsrYC2nMgZDaTC7iKwTjRe2NeM1T3Zvs=
    secure: hgy5HEAEmr/OiZRQ/DnYfC7mQX8kHu4aK3E2eI4ndbr7xdN1YffLpwhnKqsM1j1a6HuJIH8GlJDH1942EL1mETpLrwcuiAIja2cgj1u+JuqacsMzM2BSpwSII2QXwCkC64X+NFruCpo6N803qBuLIXKQoGto5pL92TuzCrFB+vZKK2vYVIufqb1WLGHjcxly8wC/tQOo3zMiyToo92ef1VnnbVOI52AX9f5pMjNQ5FccB1QzYX9ioa9IzB0U9gueX5exv8ykarOydO/wlvDamT+N78NOTJLtQRDITQ5OrTA5vrpMrUD9dyDBmIEobrSE9J8NqTacXH4msyOxEWuvDScmfpnwNMbLlRLh/KjBclZmxdD9bBm942ur0RPGu9un/2L6Pbmq2YdK5DTXQwlujQiIRPIKmBdZxGQVIylwNRRM9NroOrw8zkl9zOA8WetsssVD7ZVcuHmj8t3ci0RcJyIzq4ZGumJuYSAIYFA1u47yBgm6wgD3WMTkic8COXtuMl4HP4i2uESLPBjtWSOBRGzXM4hxSOcMgpxCC1++zq4Cl4QEVSBdCV8W0p450mk4kNjlrdfulUaOgxAe5ERdlEXtc5i4yS5rA9+gGbeiBD0V2FBiAB0xzk16pTkmMr44vqbg4H+8/ZlsPyswF2vR9kcgQmCEznrIe1IBMRbZTmU=

sudo: required
